import type { AppModule } from './schema';

export const modules: AppModule[] = [
  {
    id: 'urgencia',
    nome: 'Urgência',
    emoji: '🚨',
    descricao: 'Protocolos de tratamento por patologia com linhas terapêuticas, fármacos e sinais de alarme',
    status: 'available',
    rota: '/urgencia',
  },
  {
    id: 'vacinacao',
    nome: 'Vacinação',
    emoji: '💉',
    descricao: 'PNV 2025, vacinas extra, grupos de risco e consulta do viajante',
    status: 'available',
    rota: '/vacinacao',
  },
  {
    id: 'analises',
    nome: 'Análises',
    emoji: '🧪',
    descricao: 'Interpretador de análises — introduz o valor e recebe veredicto, raciocínio e ação clínica',
    status: 'available',
    rota: '/analises',
  },
  {
    id: 'algoritmos',
    nome: 'Algoritmos',
    emoji: '🔀',
    descricao: 'Algoritmos de diagnóstico interativos — dor no ombro e mais',
    status: 'available',
    rota: '/algoritmos',
  },
  {
    id: 'antibio',
    nome: 'Antibioterapia',
    emoji: '💊',
    descricao: 'Ferramentas clínicas de apoio à prescrição — scores, calculadoras e referências rápidas',
    status: 'available',
    rota: '/antibio',
  },
  {
    id: 'notas',
    nome: 'Notas & Dívidas',
    emoji: '📝',
    descricao: 'As tuas notas por especialidade — adiciona, edita e guarda tudo localmente',
    status: 'available',
    rota: '/notas',
  },
  {
    id: 'sintomas',
    nome: 'Sintomas',
    emoji: '🩺',
    descricao: 'Abordagem por sintoma — diagnóstico diferencial e orientação',
    status: 'soon',
  },
  {
    id: 'neuro',
    nome: 'Neurologia',
    emoji: '🧠',
    descricao: 'Protocolos neurológicos — em preparação',
    status: 'soon',
  },
];
